## GENERATED BY ANSIBLE ##
# configuration for borg job {{ item.name }} on {{ item.repository }}
{% set repo = borg_repositories[item.repository] %}
export BORG_PASSPHRASE="{{ repo.passphrase }}"
export BORG_REPO="{{ repo.user }}@{{ repo.host }}:{{ repo.path }}"
{% if repo.executable | default(False) %}
export BORG_REMOTE_PATH="{{ repo.executable }}"
{% endif %}
export BORG_RSH="ssh -i /etc/borgbackup/repositories/{{ item.repository }}.key"
export PRUNE_FLAGS='-P {{ item.archive_prefix }}- {% for interval, amount in item.prune.items() %}--keep-{{ interval }} {{ amount }} {% endfor %}'
export CREATE_FLAGS='-x{% if item.compression | default(False) %} -C {{ item.compression }}{% endif %} ::{{ item.archive_prefix }}-{utcnow} {{ item.path }}'
export JOB_PATH="{{ item.path }}"
export JOB_NAME="{{ item.name }}"
export JOB_REPO="{{ item.repository }}"
